ALTER TABLE "School"
ADD COLUMN "location" TEXT NOT NULL DEFAULT '',
ADD COLUMN "isIndependentWorkspace" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "TeacherProfile"
ADD COLUMN "fullName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "contact" TEXT NOT NULL DEFAULT '',
ADD COLUMN "subject" TEXT NOT NULL DEFAULT '',
ADD COLUMN "location" TEXT NOT NULL DEFAULT '',
ADD COLUMN "linkedin" TEXT,
ADD COLUMN "experience" TEXT NOT NULL DEFAULT '',
ADD COLUMN "education" TEXT NOT NULL DEFAULT '',
ADD COLUMN "isIndependent" BOOLEAN NOT NULL DEFAULT false;

ALTER TABLE "StudentProfile"
ADD COLUMN "fullName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "className" TEXT NOT NULL DEFAULT '',
ADD COLUMN "sectionName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "phoneNumber" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "location" TEXT NOT NULL DEFAULT '';

ALTER TABLE "ParentProfile"
ADD COLUMN "fullName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "contact" TEXT NOT NULL DEFAULT '',
ADD COLUMN "location" TEXT NOT NULL DEFAULT '';

ALTER TABLE "AdminProfile"
ADD COLUMN "fullName" TEXT NOT NULL DEFAULT '',
ADD COLUMN "email" TEXT NOT NULL DEFAULT '',
ADD COLUMN "contact" TEXT NOT NULL DEFAULT '',
ADD COLUMN "location" TEXT NOT NULL DEFAULT '',
ADD COLUMN "contactNumber" TEXT NOT NULL DEFAULT '';
