import type { NotificationEvent, NotificationEventDefinition } from "./types";

export const notificationEventCatalog: Record<NotificationEvent, NotificationEventDefinition> = {
  EXAM_GENERATED: {
    targets: [{ role: "TEACHER" }, { role: "ADMIN" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "New exam generated: {{subject}} (Class {{classLevel}})",
        body:
          "Hello {{recipientName}},\n\n" +
          "A new exam has been generated in Adhyay.\n\n" +
          "Subject: {{subject}}\n" +
          "Class: {{classLevel}}\n" +
          "Difficulty: {{difficulty}}\n" +
          "Questions: {{questionCount}}\n" +
          "Exam ID: {{examId}}\n\n" +
          "Generated by: {{actorName}}\n"
      },
      whatsapp: {
        body:
          "Adhyay: New exam generated for {{subject}} (Class {{classLevel}}). " +
          "Difficulty {{difficulty}} - {{questionCount}} questions. Exam ID: {{examId}}."
      }
    }
  },
  ANSWER_UPLOADED: {
    targets: [{ role: "STUDENT" }, { role: "PARENT" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "Answer sheet received for {{subject}} (Exam {{examId}})",
        body:
          "Hello {{recipientName}},\n\n" +
          "We received the answer sheet upload for:\n" +
          "Subject: {{subject}}\n" +
          "Exam ID: {{examId}}\n" +
          "Submission ID: {{submissionId}}\n\n" +
          "Our system is preparing the evaluation. You will be notified when the report is ready."
      },
      whatsapp: {
        body:
          "Adhyay: Answer sheet received for {{subject}} (Exam {{examId}}). " +
          "Submission ID: {{submissionId}}. We'll notify you once the report is ready."
      }
    }
  },
  TEACHER_APPROVAL_REQUEST: {
    targets: [{ role: "TEACHER" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "Review requested: submission {{submissionId}}",
        body:
          "Hello {{recipientName}},\n\n" +
          "A new answer sheet is ready for your review.\n\n" +
          "Subject: {{subject}}\n" +
          "Exam ID: {{examId}}\n" +
          "Submission ID: {{submissionId}}\n" +
          "Student ID: {{studentId}}\n\n" +
          "Please review and approve or reject the evaluation."
      },
      whatsapp: {
        body:
          "Adhyay: New submission ready for review. " +
          "Exam {{examId}}, Submission {{submissionId}}, Student {{studentId}}."
      }
    }
  },
  EVALUATION_APPROVED: {
    targets: [{ role: "STUDENT" }, { role: "PARENT" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "Evaluation approved for {{subject}} (Exam {{examId}})",
        body:
          "Hello {{recipientName}},\n\n" +
          "Your evaluation has been approved.\n\n" +
          "Subject: {{subject}}\n" +
          "Exam ID: {{examId}}\n" +
          "Submission ID: {{submissionId}}\n" +
          "Score: {{score}}\n\n" +
          "You can view the full report in Adhyay."
      },
      whatsapp: {
        body:
          "Adhyay: Evaluation approved for {{subject}} (Exam {{examId}}). " +
          "Score: {{score}}. Report available in your dashboard."
      }
    }
  },
  EVALUATION_REJECTED: {
    targets: [{ role: "STUDENT" }, { role: "PARENT" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "Evaluation needs attention for {{subject}} (Exam {{examId}})",
        body:
          "Hello {{recipientName}},\n\n" +
          "The evaluation was rejected and needs attention.\n\n" +
          "Subject: {{subject}}\n" +
          "Exam ID: {{examId}}\n" +
          "Submission ID: {{submissionId}}\n" +
          "Reason: {{rejectionReason}}\n\n" +
          "Please contact your teacher if you need help."
      },
      whatsapp: {
        body:
          "Adhyay: Evaluation rejected for {{subject}} (Exam {{examId}}). " +
          "Reason: {{rejectionReason}}."
      }
    }
  },
  REPORT_AVAILABLE: {
    targets: [{ role: "STUDENT" }, { role: "PARENT" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "Report available for {{subject}} (Exam {{examId}})",
        body:
          "Hello {{recipientName}},\n\n" +
          "Your report is now available in Adhyay.\n\n" +
          "Subject: {{subject}}\n" +
          "Exam ID: {{examId}}\n" +
          "Submission ID: {{submissionId}}\n\n" +
          "Open your dashboard to view the report."
      },
      whatsapp: {
        body:
          "Adhyay: Report available for {{subject}} (Exam {{examId}}). " +
          "Submission {{submissionId}}."
      }
    }
  },
  USAGE_LIMIT_WARNING: {
    targets: [{ role: "TEACHER" }, { role: "ADMIN" }],
    channels: ["EMAIL", "WHATSAPP"],
    templates: {
      email: {
        subject: "Usage alert: {{usagePercent}}% of monthly exam limit used",
        body:
          "Hello {{recipientName}},\n\n" +
          "Your school has used {{usedCount}} of {{limitCount}} exams this month ({{usagePercent}}%).\n" +
          "Period: {{periodStart}} to {{periodEnd}}\n\n" +
          "Consider upgrading or monitoring usage to avoid service interruptions."
      },
      whatsapp: {
        body:
          "Adhyay: Usage alert - {{usedCount}}/{{limitCount}} exams used this month ({{usagePercent}}%)."
      }
    }
  }
};
